<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Version>$(Version)</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Reactive" Version="7.0.0-preview.1" />
        <PackageReference Include="GitVersion.MsBuild" Version="6.5.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <Target Name="ConfigureTrimming" BeforeTargets="PrepareForILLink">
        <ItemGroup>
            <ManagedAssemblyToLink Condition="'%(Filename)' == 'FSharp.Control.Reactive'">
                <TrimMode>link</TrimMode>
                <IsTrimmable>true</IsTrimmable>
            </ManagedAssemblyToLink>
        </ItemGroup>
    </Target>
    
    <ItemGroup>
        <Compile Include="Disposable.fs" />
        <Compile Include="Scheduler.fs" />
        <Compile Include="Subject.fs" />
        <Compile Include="Observable.fs" />
    </ItemGroup>
    
</Project>
