<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <Version>7.0.0-preview</Version>
        <AssemblyVersion>7.0.0.0</AssemblyVersion>
        <FileVersion>7.0.0.0</FileVersion>
        <InformationalVersion>7.0.0-preview</InformationalVersion>

        <Authors>Ryan Riley;Steffen Forkmann;Jared Hester;Vladimir Likhatskiy (p1eXu5)</Authors>
        <Summary>A F#-friendly wrapper for the Reactive Extensions.</Summary>
        <Description>A F#-friendly wrapper for the Reactive Extensions.</Description>

        <PackageReadmeFile>README.md</PackageReadmeFile>

        <NeutralLanguage>en-US</NeutralLanguage>
        <RepositoryUrl>https://github.com/p1eXu5/p1eXu5.FSharp.Reactive</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/p1eXu5/p1eXu5.FSharp.Reactive</PackageProjectUrl>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageTags>F#;FSharp;Reactive Extensions;Rx;fsharp;f#;helpers;system.reactive;rx;reactive;bindings;net10;</PackageTags>

        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>

        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>

        <Deterministic>true</Deterministic>
        <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <!-- Pack the README from repo root into the nuget package -->
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Reactive.Testing" Version="7.0.0-rc.1" />
        <PackageReference Include="FParsec" Version="2.0.0-beta2" />

      <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="TestNotifications.fs" />
        <Compile Include="TestScheduler.fs" />
        <Compile Include="TestObservable.fs" />
        <Compile Include="TestObserver.fs" />
        <Compile Include="Marbles.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\p1eXu5.FSharp.Reactive\p1eXu5.FSharp.Reactive.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="FSharp.Core" Version="10.1.301" />
    </ItemGroup>

</Project>
